const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsClockwiseFrom,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Cnds.PreloadsComplete,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Audio.Acts.Preload
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Audio: 0},
	{Browser: 0},
	{Function: 0},
	{Final: 0},
	{ID: 0},
	{marker: 0},
	{Header: 0},
	{Sine: 0},
	{Game: 0},
	{Lang: 0},
	{marker2: 0},
	{Timer: 0},
	{TimerBG: 0},
	{youlose: 0},
	{Text: 0},
	{Copyright: 0},
	{"02menubg": 0},
	{"03menubg": 0},
	{"04menubg": 0},
	{"05menubg": 0},
	{bitchrun: 0},
	{menubg: 0},
	{A: 0},
	{bear: 0},
	{bitches: 0},
	{Rotate: 0},
	{button: 0},
	{Fade: 0},
	{comix: 0},
	{ComixText: 0},
	{KOMBO: 0},
	{KOMBO2: 0},
	{S1: 0},
	{S100: 0},
	{Score: 0},
	{svidetel: 0},
	{load: 0},
	{LoadText: 0},
	{AntyBaby: 0},
	{Bullet: 0},
	{bonus: 0},
	{bonus_Particles: 0},
	{TimeSlide: 0},
	{MusOnOff: 0},
	{SoundOnOff: 0},
	{FadeIN: 0},
	{FadeOUT: 0},
	{help: 0},
	{Helper: 0},
	{ClearScreen: 0},
	{ShowScreen: 0},
	{Active: 0},
	{pause: 0},
	{pause2: 0},
	{PauseText2: 0},
	{PauseText1: 0},
	{Keyboard: 0},
	{Hard: 0},
	{BitchShot: 0},
	{BestScore: 0},
	{BitchAnim: 0},
	{ButtonPush: 0},
	{Sounds: 0},
	{Music: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Final: class extends self.ITextInstance {},
	marker: class extends self.ISpriteInstance {},
	Header: class extends self.ISpriteInstance {},
	Game: class extends self.ISpriteInstance {},
	Lang: class extends self.ISpriteInstance {},
	marker2: class extends self.ISpriteInstance {},
	Timer: class extends self.ISpriteInstance {},
	TimerBG: class extends self.ISpriteInstance {},
	youlose: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Copyright: class extends self.ITextInstance {},
	_02menubg: class extends self.ISpriteInstance {},
	_03menubg: class extends self.ISpriteInstance {},
	_04menubg: class extends self.ISpriteInstance {},
	_05menubg: class extends self.ISpriteInstance {},
	bitchrun: class extends self.ISpriteInstance {},
	menubg: class extends self.ISpriteInstance {},
	bear: class extends self.ISpriteInstance {},
	bitches: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	comix: class extends self.ISpriteInstance {},
	ComixText: class extends self.ITextInstance {},
	KOMBO: class extends self.ISpriteInstance {},
	KOMBO2: class extends self.ISpriteInstance {},
	S1: class extends self.IParticlesInstance {},
	S100: class extends self.IParticlesInstance {},
	Score: class extends self.ITextInstance {},
	svidetel: class extends self.ISpriteInstance {},
	load: class extends self.ISpriteInstance {},
	LoadText: class extends self.ITextInstance {},
	AntyBaby: class extends self.ITextInstance {},
	bonus: class extends self.ISpriteInstance {},
	bonus_Particles: class extends self.IParticlesInstance {},
	TimeSlide: class extends self.ISpriteInstance {},
	MusOnOff: class extends self.ISpriteInstance {},
	SoundOnOff: class extends self.ISpriteInstance {},
	help: class extends self.ISpriteInstance {},
	Helper: class extends self.ITextInstance {},
	ClearScreen: class extends self.ITiledBackgroundInstance {},
	ShowScreen: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	pause2: class extends self.ISpriteInstance {},
	PauseText2: class extends self.ITextInstance {},
	PauseText1: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {}
}